services:
  bot:
    build: .
    container_name: expense-bot
    #network_mode: "host" # Бот использует сеть хоста напрямую  
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./logs:/app/logs
    environment:
      - TZ=Europe/Moscow
    #restart: unless-stopped
    extra_hosts:
      - "api.telegram.org:149.154.167.220"